#!/bin/bash 
#Kristina Nemeth (kan57) & Cuyler Crandall (csc254)

#first line of the file sets up the bash file
#sets up two processes with mplayer in the foreground and video_control in the background 
python SimpleServoControl.py &
python spiTest.py
